# Embeddings with PyTorch

In [1]:
import torch
import torch.nn as nn

num_categories = 1000
embedding_dim = 8

embedding = nn.Embedding(num_categories, embedding_dim)

# Example batch of categorical indices
category_indices = torch.tensor([49, 31, 521, 312])

embedded_vectors = embedding(category_indices)

print(embedded_vectors.shape)  # (batch_size, embedding_dim)

print(embedded_vectors) # the actual embeddings

torch.Size([4, 8])
tensor([[ 1.7147,  0.7614, -1.6700, -0.3169, -1.6236,  0.0110,  1.6873, -0.3070],
        [-0.3194, -0.0712, -1.3301, -0.3306, -0.1699, -0.2989,  0.8637,  0.4177],
        [ 2.3561,  0.3975,  1.1918, -0.7129, -0.0214,  0.2793, -0.3030, -0.5993],
        [ 1.3876, -0.6979, -1.3537,  0.4272, -0.5816, -0.8606, -1.1023,  0.2523]],
       grad_fn=<EmbeddingBackward0>)


# FeatureHasher 

In [2]:
from sklearn.feature_extraction import FeatureHasher

hasher = FeatureHasher(n_features=8, input_type='string')

data = [['Lancia'], ['Audi'], ['Porche'], ['Lancia']]
hashed = hasher.transform(data)

print(hashed.toarray())

[[ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]]
