In [1]:
import torch
import torch.nn as nn

# Initialize a model with 10 neurons x 4 layers
model = nn.Linear(10, 4)

print("Xavier weights initialization")
# Xavier initialization for weights
nn.init.xavier_uniform_(model.weight)
# Zero initialization for bias
nn.init.zeros_(model.bias)

# Model weights
print(model.weight)
# Model biases
print(model.bias)

print("\nHe weights initialization")
# He initialization for weights
nn.init.kaiming_normal_(model.weight, nonlinearity='relu')
# Zero initialization for bias
nn.init.zeros_(model.bias)

# Model weights
print(model.weight)
# Model biases
print(model.bias)

Xavier weights initialization
Parameter containing:
tensor([[ 0.3911,  0.2891, -0.5728, -0.2842, -0.6021,  0.0676,  0.5061,  0.5931,
         -0.6462, -0.5116],
        [-0.2852,  0.3105, -0.2620,  0.0108, -0.4024,  0.3284, -0.5561,  0.1038,
          0.0850,  0.4095],
        [-0.5773,  0.6066,  0.5743,  0.3680,  0.5220, -0.4858, -0.6034, -0.2584,
         -0.5832, -0.5720],
        [-0.1245, -0.1965, -0.2576,  0.3961, -0.2623, -0.0806, -0.2180, -0.5548,
         -0.3834,  0.2974]], requires_grad=True)
Parameter containing:
tensor([0., 0., 0., 0.], requires_grad=True)

He weights initialization
Parameter containing:
tensor([[ 0.3517,  0.9961, -0.6612, -0.2764, -0.2139, -0.1365,  0.1516,  0.1059,
          0.0803, -0.5622],
        [ 0.0790, -0.1939, -0.7055,  0.6034,  0.3407,  0.1818, -0.4567, -0.3591,
         -1.0500, -0.2565],
        [ 0.7301,  0.5112,  0.0762,  0.0381, -0.5629, -0.2248,  0.4980,  0.2976,
          0.3878, -1.1902],
        [-0.3801,  0.8775, -0.0619,  0.4265,  0.